### ISSUE TITLE
remove generated but tracked files from repo

### ISSUE THREAD

**Issue by gregito** [BenTrk/kisgeri24#113]
for example:
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift

**Comment by gregito** [comment]
not sure what else files could be affected since I'm working from Mac OS thus I'd have different files tracked than Windows or Linux users

**Comment by terjekig** [comment]
These files unfortunately survived [the purge](https://github.com/BenTrk/kisgeri24/pull/98)
