### ISSUE TITLE
Adding a start button on the main page, to start the climbing time countdown

### ISSUE THREAD

**Issue by lmarti95** [BenTrk/kisgeri24#61]

**Comment by bijancska** [comment]
elkészült

![Image](https://github.com/BenTrk/kisgeri24/assets/147754859/73491a2a-75ba-4ea6-a727-55cf8b69c8d9)

**Comment by TerjekiG** [comment]
Esetleg itt ki lehetne írni, hogy akkor meddig is mászhat az ember, mikor van vége neki?
