### ISSUE TITLE
Add generated files to gitignore

### ISSUE THREAD

**Issue by terjekig** [BenTrk/kisgeri24#96]
`windows/flutter/generated_plugin_registrant.cc` and `windows/flutter/generated_plugins.cmake` always pop up in my git status. I'd like to extend gitignore to ignore these files.

**Comment by gregito** [comment]
`/linux/`, `/macos/`, `/web/`, `/windows/`, `/ios/` should be fine?

**Comment by gregito** [comment]
also `/android/`?

**Comment by terjekig** [comment]
Platform folders can have configuration settings we should share (like AndroidManifest.xml), therefore I'd only add the generated files to the ignore list. (They were already added for the android and ios folders by you :D)
